version: '3.8'

services:
  # Service de l'application Node.js
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api_container
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://root:example@mongo:27017/api-mongoose?authSource=admin
      - PORT=5000
    restart: unless-stopped

  # Service MongoDB
  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    restart: unless-stopped

volumes:
  mongo_data:
